version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobile-marketplace-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: